spring.application.name=book-management

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.audiences=${AUTH0_AUDIENCE}
google.books.api.key=${GOOGLE_BOOKS_API_KEY}
spring.datasource.url=jdbc:h2:mem:dbbook
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console